/**
 * Receiving what AfriZoneMart tells us (Blueprint §5, MART_INTEGRATION.md §2-3).
 *
 * Mart sends facts. This decides what work each one creates, records what it
 * did, and makes a retry free.
 *
 * TWO KINDS OF DUPLICATE, AND THEY NEED DIFFERENT ANSWERS. `eventId` stops the
 * same DELIVERY being processed twice - Mart retrying after a timeout. A
 * per-type de-duplication rule stops duplicate WORK - a shelf that stays empty
 * emitting stock.low every hour. Neither substitutes for the other, and a system
 * with only the first sends four auditors to one shop.
 */
import crypto from "crypto";
import { prisma } from "../prisma";
import { generateTask } from "./taskGenerator";
import { requestStoreAudit } from "./storeAudit";
import { userActor, type AuditActor } from "../util/audit";

export const MART_EVENT_TYPES = [
  "order.confirmed",
  "stock.low",
  "store.applied",
  "listing.needs_media",
] as const;
export type MartEventType = (typeof MART_EVENT_TYPES)[number];

/** How long a signed request stays valid. */
const SIGNATURE_WINDOW_SECONDS = 5 * 60;

export type VerifyResult = { ok: true } | { ok: false; error: string };

/**
 * Check the signature and the clock.
 *
 * The timestamp is INSIDE the signed string, not merely sent alongside it -
 * otherwise it can be changed freely and buys nothing. Paystack's own scheme has
 * no timestamp and is replayable; we control both ends here, so this does not
 * copy that.
 */
export function verifyMartSignature(
  rawBody: Buffer | string,
  timestamp: string | undefined,
  signature: string | undefined,
  secret: string | undefined,
  now: Date = new Date()
): VerifyResult {
  if (!secret) return { ok: false, error: "Integration is not configured" };
  if (!timestamp || !signature) return { ok: false, error: "Missing signature headers" };

  const ts = Number(timestamp);
  if (!Number.isFinite(ts)) return { ok: false, error: "Bad timestamp" };
  const skew = Math.abs(Math.floor(now.getTime() / 1000) - ts);
  if (skew > SIGNATURE_WINDOW_SECONDS) return { ok: false, error: "Timestamp outside window" };

  // worker-configuration.d.ts (generated by `wrangler types`) declares a global
  // `Buffer: any` that shadows @types/node's real class at the type level, so
  // the encoding-aware toString() overload becomes invisible even though the
  // runtime supports it fully. Same narrow cast the Paystack webhook uses.
  const body = typeof rawBody === "string" ? rawBody : (rawBody as any).toString("utf8");
  const expected = crypto.createHmac("sha256", secret).update(`${timestamp}.${body}`).digest("hex");

  // Timing-safe: a byte-by-byte comparison on an HMAC leaks its own answer.
  const a = Buffer.from(expected);
  const b = Buffer.from(signature);
  if (a.length !== b.length) return { ok: false, error: "Bad signature" };
  if (!crypto.timingSafeEqual(a, b)) return { ok: false, error: "Bad signature" };
  return { ok: true };
}


/**
 * The payload is stored base64-encoded, and that is a workaround rather than a
 * design choice - it is documented here so nobody removes it and re-breaks the
 * endpoint.
 *
 * REPRODUCTION. Storing the raw JSON in this TEXT column makes every subsequent
 * Prisma read of the row fail under `wrangler dev` with:
 *
 *     Inconsistent column data: Conversion failed:
 *     expected a datetime string in column 'payload', found {"eventId":...
 *
 * It happens if and only if the JSON contains an ISO-8601 datetime substring -
 * an event body carrying `occurredAt` always does. A payload with no datetime
 * text in it round-trips fine. The row is written correctly either way; it is
 * only mapping the returned row that fails, so INSERT...RETURNING breaks too and
 * `create()` throws.
 *
 * WHAT I COULD NOT EXPLAIN. The same code, adapter and payload pass under
 * vitest-pool-workers against its own D1, so the test suite never saw this. That
 * difference is unexplained, which is exactly why this is belt-and-braces rather
 * than a targeted fix: encoding removes the trigger everywhere instead of
 * relying on an environment behaving.
 *
 * The cost is that the column is not eyeball-readable in a database browser.
 * Anything that shows it to a person decodes it first.
 */
function encodePayload(body: unknown): string {
  return Buffer.from(JSON.stringify(body), "utf8").toString("base64");
}

/** Read a stored payload back. Tolerates plain JSON, for rows written before this. */
export function decodePayload(stored: string): unknown {
  try {
    const text = Buffer.from(stored, "base64").toString("utf8");
    return JSON.parse(text);
  } catch {
    try {
      return JSON.parse(stored);
    } catch {
      return null;
    }
  }
}

export type IntakeResult =
  | { status: 200 | 201 | 202; body: Record<string, unknown> }
  | { status: 400; body: { error: string } };

interface Envelope {
  eventId?: unknown;
  type?: unknown;
  occurredAt?: unknown;
  data?: Record<string, any>;
}

/**
 * Take one event.
 *
 * Returns the HTTP shape the caller should send back, per the response table in
 * MART_INTEGRATION.md §2 - notably 200 for a repeat and 202 for "understood, no
 * work created". A retry is the system working correctly, and answering it with
 * an error makes Mart's alerting fire on success.
 */
export async function intakeMartEvent(body: Envelope, actor?: AuditActor): Promise<IntakeResult> {
  const eventId = typeof body?.eventId === "string" ? body.eventId : null;
  const type = typeof body?.type === "string" ? body.type : null;
  if (!eventId) return { status: 400, body: { error: "eventId is required" } };
  if (!type || !MART_EVENT_TYPES.includes(type as MartEventType)) {
    return { status: 400, body: { error: `type must be one of ${MART_EVENT_TYPES.join(", ")}` } };
  }
  const occurredAt = body?.occurredAt ? new Date(String(body.occurredAt)) : new Date();
  if (Number.isNaN(occurredAt.getTime())) {
    return { status: 400, body: { error: "occurredAt is not a date" } };
  }

  // Already seen. Not an error - see the note above.
  const seen = await prisma.martEvent.findUnique({ where: { eventId } });
  if (seen) {
    return {
      status: 200,
      body: { eventId, status: seen.status, taskId: seen.resultTaskId, duplicate: true },
    };
  }

  const admin = await prisma.user.findFirst({
    where: { role: "SUPER_ADMIN" },
    select: { id: true },
  });
  // Attributed to a real person where one exists, so the audit trail does not
  // dead-end at "the system".
  const who: AuditActor = actor ?? (admin ? userActor(admin.id) : { type: "INTEGRATION", ref: "afrizone-mart" });

  const data = (body?.data ?? {}) as Record<string, any>;
  let outcome: { status: string; taskId: string | null; note: string | null };

  try {
    outcome = await handle(type as MartEventType, data, who);
  } catch (e) {
    outcome = {
      status: "FAILED",
      taskId: null,
      note: e instanceof Error ? e.message : "Could not process",
    };
  }

  await prisma.martEvent.create({
    data: {
      eventId,
      type,
      occurredAt,
      payload: encodePayload(body),
      status: outcome.status,
      resultTaskId: outcome.taskId,
      note: outcome.note,
    },
  });

  if (outcome.status === "FAILED") {
    return { status: 400, body: { error: outcome.note ?? "Could not process" } };
  }
  // Keyed on whether WORK WAS CREATED, not on whether a taskId came back. A
  // de-duplicated event returns the id of the task that already covers it -
  // which is useful to Mart - but answering 201 for it would tell them a second
  // task exists. 202 is "understood, nothing new came of it", and Mart must not
  // treat that as a failure.
  return {
    status: outcome.status === "PROCESSED" ? 201 : 202,
    body: { eventId, status: outcome.status, taskId: outcome.taskId, note: outcome.note },
  };
}

async function handle(
  type: MartEventType,
  data: Record<string, any>,
  actor: AuditActor
): Promise<{ status: string; taskId: string | null; note: string | null }> {
  switch (type) {
    case "stock.low":
      return handleStockLow(data, actor);
    case "store.applied":
      return handleStoreApplied(data, actor);
    case "listing.needs_media":
      return handleNeedsMedia(data, actor);
    case "order.confirmed":
      return handleOrderConfirmed();
  }
}

/** A shelf is empty. Send somebody to find stock. */
async function handleStockLow(data: Record<string, any>, actor: AuditActor) {
  const sku = String(data.sku ?? "").trim();
  const productName = String(data.productName ?? sku).trim();
  if (!sku) throw new Error("stock.low needs a sku");
  const region = String(data.region ?? "").trim();

  // De-duplicated on sku + region: one open sourcing task per product per area.
  // Without this a shelf that stays empty for a day produces a task an hour.
  const res = await generateTask({
    kind: "SOURCING",
    title: `Source ${productName}${region ? ` (${region})` : ""}`,
    description: `${productName} is out of stock${
      data.currentQty != null ? ` (${data.currentQty} on hand` : ""
    }${data.reorderThreshold != null ? `, reorder at ${data.reorderThreshold})` : data.currentQty != null ? ")" : ""}. Find and secure replacement stock${
      data.targetQty != null ? `, target ${data.targetQty} units` : ""
    }.`,
    category: "Sourcing",
    locationType: "PHYSICAL",
    dedupe: { field: "title", value: `Source ${productName}${region ? ` (${region})` : ""}` },
    actor,
  });
  return toOutcome(res, "sourcing");
}

/**
 * A store wants to join. Register it as PENDING and send an auditor.
 *
 * PartTime owns the store record - that was settled - so this creates the
 * Organization rather than expecting Mart to have one. Mart is forwarding a
 * lead, not handing over a business.
 */
async function handleStoreApplied(data: Record<string, any>, actor: AuditActor) {
  const applicationId = String(data.applicationId ?? "").trim();
  const name = String(data.businessName ?? "").trim();
  if (!name) throw new Error("store.applied needs a businessName");

  const slug = `mart-${applicationId || name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`.slice(0, 64);
  let org = await prisma.organization.findUnique({ where: { slug } });
  if (!org) {
    org = await prisma.organization.create({
      data: {
        kind: "STORE",
        name,
        slug,
        address: data.address ? String(data.address) : null,
        lat: data.lat != null ? Number(data.lat) : null,
        lng: data.lng != null ? Number(data.lng) : null,
        phone: data.contact?.phone ? String(data.contact.phone) : null,
        email: data.contact?.email ? String(data.contact.email) : null,
        tin: data.registration?.tin ? String(data.registration.tin) : null,
        // Approved by a person, after an audit. Never on arrival.
        status: "PENDING",
      },
    });
  }

  const audit = await requestStoreAudit(org.id, actor);
  if (!audit) {
    return {
      status: "IGNORED",
      taskId: null,
      note: "Registered, but no audit raised (already approved, or no address)",
    };
  }
  return {
    status: audit.created ? "PROCESSED" : "IGNORED",
    taskId: audit.taskId,
    note: audit.created ? null : "An audit was already open for this store",
  };
}

/** A listing has no pictures. */
async function handleNeedsMedia(data: Record<string, any>, actor: AuditActor) {
  const listingId = String(data.listingId ?? "").trim();
  const productName = String(data.productName ?? listingId).trim();
  if (!listingId) throw new Error("listing.needs_media needs a listingId");
  const need = Array.isArray(data.need) ? data.need.join(", ") : "photographs";

  const title = `Photograph ${productName}`;
  const res = await generateTask({
    kind: "MEDIA",
    title,
    description: `${productName} needs ${need} for its AfriZoneMart listing.`,
    category: "Media",
    dedupe: { field: "title", value: title },
    actor,
  });
  return toOutcome(res, "media");
}

/**
 * An order was placed. Recorded, but nothing is generated yet.
 *
 * Delivery does not exist - no assignment path, no pickup and drop-off, no
 * customer OTP - so there is nothing correct to create. Answering 200 and
 * silently dropping it would lose the order; recording it DEFERRED means every
 * one of them can be replayed the day delivery ships. That is the whole reason
 * the event ledger exists rather than a bare idempotency key.
 */
async function handleOrderConfirmed() {
  return {
    status: "DEFERRED",
    taskId: null,
    note: "Delivery is not built yet. Recorded for replay.",
  };
}

function toOutcome(
  res: Awaited<ReturnType<typeof generateTask>>,
  what: string
): { status: string; taskId: string | null; note: string | null } {
  if (res.created) return { status: "PROCESSED", taskId: res.taskId, note: null };
  if (res.reason === "DUPLICATE") {
    return { status: "IGNORED", taskId: res.taskId, note: `An open ${what} task already covers this` };
  }
  return { status: "FAILED", taskId: null, note: `Could not create a ${what} task: ${res.reason}` };
}
