/**
 * Store premises audits (Blueprint §8).
 *
 * A store goes apply -> audit -> approve -> live on the map. This handles the
 * middle step, and the shape of it is the point: an audit is not a workflow
 * bolted onto the store record, it is **a Task**. It is paid work, somebody has
 * to claim it, and only somebody carrying an auditor credential may - all of
 * which the task and eligibility machinery already does. Building a parallel
 * inspection system would have meant a second way to pay people and a second
 * definition of "qualified".
 *
 * WHY THE PARAMETERS ARE SETTINGS AND NOT CONSTANTS. Blueprint §5 asks that
 * generation rules - "thresholds, target radius, required skill role, pay band"
 * - stay Admin-editable rather than hard-coded, and this is the first generator
 * to exist. Raising the audit fee should be a change somebody makes on a screen,
 * not a deploy.
 */
import { prisma } from "../prisma";
import { userActor, writeAudit, type AuditActor } from "../util/audit";

export type AuditOutcome = "PASS" | "FAIL";
export const AUDIT_OUTCOMES: AuditOutcome[] = ["PASS", "FAIL"];

/** Settings keys, with the defaults used when nobody has set them. */
export const AUDIT_SETTINGS = {
  fee: { key: "audit.fee", fallback: 15000 },
  /**
   * Which tier auditors are drawn from.
   *
   * A STOPGAP, and worth understanding before someone "fixes" it. The blueprint
   * describes Auditor as a SKILL ROLE, and the platform has no skill roles yet -
   * only tiers, none of which means "auditor". What actually gates the work is
   * the credential requirement below; the tier just has to be one real workers
   * hold, so it is configurable rather than invented in code.
   */
  tier: { key: "audit.tier", fallback: "TRADE" },
  /** The credential that makes somebody an auditor. */
  credentialSlug: { key: "audit.credential", fallback: "auditor-accreditation" },
  /** At or above this score, the premises pass. */
  passMark: { key: "audit.passMark", fallback: 70 },
  /** Days an auditor has to claim and complete it. */
  windowDays: { key: "audit.windowDays", fallback: 7 },
};

async function setting<T extends string | number>(
  key: string,
  fallback: T
): Promise<T> {
  const row = await prisma.setting.findUnique({ where: { key } });
  if (!row) return fallback;
  if (typeof fallback === "number") {
    const n = Number(row.value);
    return (Number.isFinite(n) ? n : fallback) as T;
  }
  return (row.value || fallback) as T;
}

/** PASS or FAIL, decided against the configured mark at the time of the audit. */
export async function outcomeFor(score: number): Promise<AuditOutcome> {
  const mark = await setting(AUDIT_SETTINGS.passMark.key, AUDIT_SETTINGS.passMark.fallback);
  return score >= mark ? "PASS" : "FAIL";
}

/**
 * Generate the inspection task for a store that is waiting to be approved.
 *
 * Idempotent by design rather than by constraint: if an audit task for this
 * organization is already open, it is returned rather than a second one being
 * created. Two auditors dispatched to the same shop is a real cost to somebody,
 * not a tidy-database concern.
 *
 * Returns null when there is nothing to do - an already-active store does not
 * need inspecting, and a store with no address cannot be visited.
 */
export async function requestStoreAudit(
  organizationId: string,
  requestedBy: AuditActor
): Promise<{ taskId: string; created: boolean } | null> {
  const org = await prisma.organization.findUnique({ where: { id: organizationId } });
  if (!org) return null;
  // An approved store is not waiting on an inspection. Re-auditing a live store
  // is a recurring compliance check (Blueprint §2), which is a different thing
  // and is not this.
  if (org.status === "ACTIVE") return null;
  // Somebody has to be able to go there.
  if (!org.address && (org.lat == null || org.lng == null)) return null;

  const existing = await prisma.task.findFirst({
    where: {
      kind: "STORE_AUDIT",
      organizationId,
      status: { in: ["OPEN", "FILLED"] },
    },
    select: { id: true },
  });
  if (existing) return { taskId: existing.id, created: false };

  const [fee, tier, credentialSlug, windowDays] = await Promise.all([
    setting(AUDIT_SETTINGS.fee.key, AUDIT_SETTINGS.fee.fallback),
    setting(AUDIT_SETTINGS.tier.key, AUDIT_SETTINGS.tier.fallback),
    setting(AUDIT_SETTINGS.credentialSlug.key, AUDIT_SETTINGS.credentialSlug.fallback),
    setting(AUDIT_SETTINGS.windowDays.key, AUDIT_SETTINGS.windowDays.fallback),
  ]);

  const deadline = new Date(Date.now() + windowDays * 24 * 60 * 60 * 1000);
  const admin = await prisma.user.findFirst({
    where: { role: "SUPER_ADMIN" },
    select: { id: true },
  });
  // createdById is attribution and the column is required. An audit generated by
  // the platform is still attributed to a person where one is available, so the
  // trail does not dead-end at "the system".
  const createdById = requestedBy.userId ?? admin?.id;
  if (!createdById) return null;

  const task = await prisma.task.create({
    data: {
      kind: "STORE_AUDIT",
      organizationId,
      title: `Store audit: ${org.name}`,
      description: `Visit ${org.name}${org.address ? ` at ${org.address}` : ""}, verify the premises against the AfriZone standard, and score them. Record what you find - an approval rests on it.`,
      category: "Audit",
      tier,
      payModel: "FIXED",
      budget: fee,
      startDate: new Date(),
      endDate: deadline,
      locationType: "PHYSICAL",
      address: org.address,
      lat: org.lat,
      lng: org.lng,
      slots: 1,
      status: "OPEN",
      deadline,
      createdById,
      // An audit is exactly the case Blueprint §3.1 gives for gating: "a store
      // audit requires a verified auditor credential".
      requiresIdentityVerified: true,
    },
  });

  const credential = await prisma.credentialType.findUnique({
    where: { slug: credentialSlug },
    select: { id: true, name: true },
  });
  if (credential) {
    await prisma.taskCredentialRequirement.create({
      data: { taskId: task.id, credentialTypeId: credential.id },
    });
    await prisma.task.update({
      where: { id: task.id },
      data: {
        requirementsSummary: `ID confirmed · ${credential.name}`,
        requirementsVersion: 1,
      },
    });
  }
  // No credential type configured means an ungated audit task, which is worse
  // than none - anybody could inspect a shop. Said loudly in the audit trail
  // rather than failing silently.
  else {
    await writeAudit(requestedBy, "store.audit.ungated", "Task", task.id, {
      organizationId,
      missingCredentialSlug: credentialSlug,
    });
  }

  await writeAudit(requestedBy, "store.audit.requested", "Organization", organizationId, {
    taskId: task.id,
    fee,
    tier,
  });

  return { taskId: task.id, created: true };
}

/** The most recent finding for a store, which is what an approval rests on. */
export async function latestAudit(organizationId: string) {
  return prisma.storeAudit.findFirst({
    where: { organizationId },
    orderBy: { createdAt: "desc" },
    include: { auditor: { select: { id: true, name: true } } },
  });
}

/** Record what an auditor found. */
export async function recordAudit(input: {
  organizationId: string;
  taskId?: string | null;
  auditorId?: string | null;
  score: number;
  notes?: string | null;
  actor: AuditActor;
}) {
  const outcome = await outcomeFor(input.score);
  const row = await prisma.storeAudit.create({
    data: {
      organizationId: input.organizationId,
      taskId: input.taskId ?? null,
      auditorId: input.auditorId ?? null,
      score: input.score,
      outcome,
      notes: input.notes ?? null,
    },
  });
  await writeAudit(input.actor, "store.audit.recorded", "Organization", input.organizationId, {
    storeAuditId: row.id,
    score: input.score,
    outcome,
    taskId: input.taskId ?? null,
  });
  return row;
}

export { userActor };
