import { Router, Request, Response } from "express";
import { prisma } from "../prisma";
import { paystack } from "../services/paystack";
import { verifyWebhookSignature, isApprovedResultCode } from "../services/smileIdentity";
import { notifyWorker } from "../services/push";

const router = Router();

// POST /api/webhooks/paystack
// Receives transfer.* events (outbound payouts → Withdrawal) and charge.*
// events (inbound platform funding → Funding). The raw body is needed for
// signature verification: index.ts mounts express.raw() on this path BEFORE
// the global express.json().
router.post("/paystack", async (req: Request, res: Response) => {
  const signature = req.header("x-paystack-signature");
  const raw: Buffer = Buffer.isBuffer(req.body) ? req.body : Buffer.from(JSON.stringify(req.body));

  if (!paystack.verifyWebhook(raw, signature)) {
    return res.status(401).json({ error: "Invalid signature" });
  }

  let event: any;
  try {
    // `worker-configuration.d.ts` (generated by `wrangler types`) declares its
    // own global `Buffer: any` that shadows @types/node's real Buffer class at
    // the type level - Buffer.prototype's encoding-aware toString() overload
    // becomes invisible, even though nodejs_compat's actual runtime Buffer
    // still supports it fully. Compile-time-only conflict; cast is narrow and
    // scoped to these known call sites, not a general escape hatch.
    event = JSON.parse((raw as any).toString("utf8"));
  } catch {
    return res.status(400).json({ error: "Bad payload" });
  }

  const type: string = event?.event || "";
  const data = event?.data || {};
  const reference: string | undefined = data.reference;
  const transferCode: string | undefined = data.transfer_code;

  // Locate the withdrawal by our reference (preferred) or Paystack transfer_code.
  const withdrawal = await prisma.withdrawal.findFirst({
    where: {
      OR: [reference ? { reference } : undefined, transferCode ? { providerRef: transferCode } : undefined].filter(
        Boolean
      ) as any,
    },
  });

  if (withdrawal) {
    if (type === "transfer.success") {
      await prisma.withdrawal.update({ where: { id: withdrawal.id }, data: { status: "PAID" } });
    } else if (type === "transfer.failed" || type === "transfer.reversed") {
      await prisma.withdrawal.update({
        where: { id: withdrawal.id },
        data: { status: "FAILED", failureReason: data.reason || type },
      });
    }
  } else if (type === "charge.success" || type === "charge.failed") {
    // Locate the funding by our reference (preferred) or Paystack access_code.
    const accessCode: string | undefined = data.access_code;
    const funding = await prisma.funding.findFirst({
      where: {
        OR: [reference ? { reference } : undefined, accessCode ? { providerRef: accessCode } : undefined].filter(
          Boolean
        ) as any,
      },
    });
    if (funding && funding.status === "PENDING") {
      await prisma.funding.update({
        where: { id: funding.id },
        data: { status: type === "charge.success" ? "SUCCESS" : "FAILED" },
      });
    }
  }

  // Always 200 so Paystack stops retrying.
  res.json({ received: true });
});

// POST /api/webhooks/smile
// Final result for a Document Verification job, including ones that needed human
// review (which the synchronous return_job_status result in routes/me.ts can't
// reflect: see services/smileIdentity.ts). Only relevant when SMILE_CALLBACK_URL
// points here; without it Smile has nowhere to send this and the sync result stands.
router.post("/smile", async (req: Request, res: Response) => {
  const body = req.body || {};
  const { timestamp, signature, ResultCode, ResultText, SmileJobID, PartnerParams } = body;

  if (!(await verifyWebhookSignature(String(timestamp ?? ""), String(signature ?? "")))) {
    return res.status(401).json({ error: "Invalid signature" });
  }

  const jobId = PartnerParams?.job_id ? String(PartnerParams.job_id) : undefined;
  const verification = jobId
    ? await prisma.kycVerification.findUnique({ where: { jobId } })
    : null;

  if (verification) {
    const approved = isApprovedResultCode(ResultCode);
    await prisma.kycVerification.update({
      where: { id: verification.id },
      data: {
        smileJobId: SmileJobID ?? verification.smileJobId,
        status: approved ? "APPROVED" : "REJECTED",
        resultCode: ResultCode ?? verification.resultCode,
        resultText: ResultText ?? verification.resultText,
        raw: JSON.stringify(body),
      },
    });
    await prisma.user.update({
      where: { id: verification.workerId },
      data: {
        kycStatus: approved ? "VERIFIED" : "REJECTED",
        kycNote: approved ? null : ResultText || "Automated verification did not pass.",
      },
    });

    await notifyWorker(
      prisma,
      verification.workerId,
      approved ? "Identity verified ✅" : "Verification not approved",
      approved
        ? "Your identity has been verified. You can now apply to tasks."
        : "Your verification wasn't approved. Check the app for details and re-verify.",
      { screen: "kyc" },
      "notifTasks"
    );
  }

  // Always 200 so Smile ID stops retrying.
  res.json({ received: true });
});

export default router;
